const fontOptions = [
	{ value: 'Arial, sans-serif', label: 'Arial' },
	{ value: 'Helvetica, sans-serif', label: 'Helvetica' },
	{ value: 'Times New Roman, serif', label: 'Times New Roman' },
	{ value: 'Georgia, serif', label: 'Georgia' },
	{ value: 'Open Sans, sans-serif', label: 'Open Sans' },
	{ value: 'Roboto, sans-serif', label: 'Roboto' },
	{ value: 'Roboto Serif, serif', label: 'Roboto Serif' },
	{ value: 'Roboto Condensed, sans-serif', label: 'Roboto Condensed' },
	{ value: 'Roboto Mono, monospace', label: 'Roboto Mono' },
	{ value: 'Lato, sans-serif', label: 'Lato' },
	{ value: 'Montserrat, sans-serif', label: 'Montserrat' },
	{
		value: 'Montserrat Alternates, sans-serif',
		label: 'Montserrat Alternates',
	},
	{ value: 'Raleway, sans-serif', label: 'Raleway' },
	{ value: 'Poppins, sans-serif', label: 'Poppins' },
	{ value: 'Roboto Slab, serif', label: 'Roboto Slab' },
	{ value: 'Playfair Display, serif', label: 'Playfair Display' },
	{ value: 'Playfair, serif', label: 'Playfair' },
	{ value: 'Nunito Sans, sans-serif', label: 'Nunito Sans' },
	{ value: 'Noto Sans, sans-serif', label: 'Noto Sans' },
	{ value: 'Oswald, sans-serif', label: 'Oswald' },
	{ value: 'Ubuntu, sans-serif', label: 'Ubuntu' },
	{ value: 'Nunito, sans-serif', label: 'Nunito' },
	{ value: 'Rubik, sans-serif', label: 'Rubik' },
	{ value: 'Merriweather, serif', label: 'Merriweather' },
	{ value: 'PT Sans, sans-serif', label: 'PT Sans' },
	{ value: 'Kanit, sans-serif', label: 'Kanit' },
	{ value: 'Mukta, sans-serif', label: 'Mukta' },
	{ value: 'Lora, serif', label: 'Lora' },
	{ value: 'Marcellus, serif', label: 'Marcellus' },
	{ value: 'Marcellus SC, serif', label: 'Marcellus SC' },
	{ value: 'Work Sans, sans-serif', label: 'Work Sans' },
	{ value: 'Quicksand, sans-serif', label: 'Quicksand' },
	{ value: 'Barlow, sans-serif', label: 'Barlow' },
	{
		value: 'Barlow Semi Condensed, sans-serif',
		label: 'Barlow Semi Condensed',
	},
	{ value: 'Heebo, sans-serif', label: 'Heebo' },
	{ value: 'DM Sans, sans-serif', label: 'DM Sans' },
	{ value: 'Mulish, sans-serif', label: 'Mulish' },
	{ value: 'IBM Plex Sans, sans-serif', label: 'IBM Plex Sans' },
	{ value: 'PT Serif, serif', label: 'PT Serif' },
	{ value: 'Titillium Web, sans-serif', label: 'Titillium Web' },
	{ value: 'Libre Franklin, sans-serif', label: 'Libre Franklin' },
	{ value: 'Inter, sans-serif', label: 'Inter' },
	{ value: 'Manrope, sans-serif', label: 'Manrope' },
	{ value: 'Inconsolata, monospace', label: 'Inconsolata' },
	{ value: 'Nanum Gothic, sans-serif', label: 'Nanum Gothic' },
	{ value: 'Josefin Sans, sans-serif', label: 'Josefin Sans' },
	{ value: 'Karla, sans-serif', label: 'Karla' },
	{ value: 'Dosis, sans-serif', label: 'Dosis' },
	{ value: 'PT Sans Narrow, sans-serif', label: 'PT Sans Narrow' },
	{ value: 'Space Grotesk, sans-serif', label: 'Space Grotesk' },
	{ value: 'Oxygen, sans-serif', label: 'Oxygen' },
	{ value: 'Bebas Neue, sans-serif', label: 'Bebas Neue' },
	{ value: 'Abel, sans-serif', label: 'Abel' },
	{ value: 'Assistant, sans-serif', label: 'Assistant' },
	{ value: 'Cabin, sans-serif', label: 'Cabin' },
	{ value: 'Bitter, serif', label: 'Bitter' },
	{ value: 'Anton, sans-serif', label: 'Anton' },
	{ value: 'EB Garamond, serif', label: 'EB Garamond' },
	{ value: 'Barlow Condensed, sans-serif', label: 'Barlow Condensed' },
	{ value: 'Jost, sans-serif', label: 'Jost' },
	{ value: 'Hind, sans-serif', label: 'Hind' },
	{ value: 'Source Code Pro, monospace', label: 'Source Code Pro' },
	{ value: 'Maven Pro, sans-serif', label: 'Maven Pro' },
	{ value: 'Prompt, sans-serif', label: 'Prompt' },
	{ value: 'Martel Sans, sans-serif', label: 'Martel Sans' },
	{ value: 'Crimson Text, serif', label: 'Crimson Text' },
	{ value: 'Signika Negative, sans-serif', label: 'Signika Negative' },
	{ value: 'Fjalla One, sans-serif', label: 'Fjalla One' },
	{ value: 'Outfit, sans-serif', label: 'Outfit' },
	{ value: 'Rajdhani, sans-serif', label: 'Rajdhani' },
	{ value: 'Catamaran, sans-serif', label: 'Catamaran' },
	{ value: 'Comfortaa, cursive', label: 'Comfortaa' },
	{ value: 'Poiret One, cursive', label: 'Poiret One' },
	{ value: 'Exo, sans-serif', label: 'Exo' },
	{ value: 'Exo 2, sans-serif', label: 'Exo 2' },
	{ value: 'Signika, sans-serif', label: 'Signika' },
	{ value: 'Signika Negative, sans-serif', label: 'Signika Negative' },
	{ value: 'Patua One, cursive', label: 'Patua One' },
	{ value: 'Hammersmith One, sans-serif', label: 'Hammersmith One' },
	{ value: 'Alegreya Sans, sans-serif', label: 'Alegreya Sans' },
	{ value: 'Alegreya Sans SC, sans-serif', label: 'Alegreya Sans Sc' },
	{ value: 'Pacifico, cursive', label: 'Pacifico' },
	{ value: 'Orbitron, sans-serif', label: 'Orbitron' },
	{ value: 'Zilla Slab, serif', label: 'Zilla Slab' },
	{ value: 'Great Vibes, cursive', label: 'Great Vibes' },
	{ value: 'Comic Neue, cursive', label: 'Comic Neue' },
	{ value: 'Bree Serif, serif', label: 'Bree Serif' },
	{ value: 'Domine, serif', label: 'Domine' },
	{ value: 'Cardo, serif', label: 'Cardo' },
	{ value: 'Notable, sans-serif', label: 'Notable' },
	{ value: 'Varela Round, sans-serif', label: 'Varela Round' },
	{ value: 'Cutive Mono, monospace', label: 'Cutive Mono' },
	{ value: 'Darker Grotesque, sans-serif', label: 'Darker Grotesque' },
	{ value: 'Overpass, sans-serif', label: 'Overpass' },
	{ value: 'Overpass Mono, monospace', label: 'Overpass Mono' },
	{ value: 'Istok Web, sans-serif', label: 'Istok Web' },
	{ value: 'Asap, sans-serif', label: 'Asap' },
	{ value: 'Asap, sans-serif', label: 'Asap' },
	{ value: 'Fira Sans, sans-serif', label: 'Fira Sans' },
	{ value: 'Fira Sans Condensed, sans-serif', label: 'Fira Sans Condensed' },
	{
		value: 'Fira Sans Extra Condensed, sans-serif',
		label: 'Fira Sans Extra Condensed',
	},
	{ value: 'Archivo, sans-serif', label: 'Archivo' },
	{ value: 'Public Sans, sans-serif', label: 'Public Sans' },
	{ value: 'REM, sans-serif', label: 'REM' },
	{ value: 'Urbanist, sans-serif', label: 'Urbanist' },
	{ value: 'Chivo, sans-serif', label: 'Chivo' },
	{ value: 'Noto Sans Display, sans-serif', label: 'Noto Sans Display' },
	{ value: 'Noto Sans Adlam, sans-serif', label: 'Noto Sans Adlam' },
	{ value: 'Noto Sans Armenian, sans-serif', label: 'Noto Sans Armenian' },
	{ value: 'Noto Sans Avestan, sans-serif', label: 'Noto Sans Avestan' },
	{ value: 'Noto Sans Balinese, sans-serif', label: 'Noto Sans Balinese' },
	{ value: 'Noto Sans Bamum, sans-serif', label: 'Noto Sans Bamum' },
	{ value: 'Noto Sans Bassa Vah, sans-serif', label: 'Noto Sans Bassa Vah' },
	{ value: 'Noto Sans Batak, sans-serif', label: 'Noto Sans Batak' },
	{ value: 'Noto Sans Bengali, sans-serif', label: 'Noto Sans Bengali' },
	{ value: 'Noto Sans Brahmi, sans-serif', label: 'Noto Sans Brahmi' },
	{ value: 'Noto Sans Buginese, sans-serif', label: 'Noto Sans Buginese' },
	{ value: 'Noto Sans Buhid, sans-serif', label: 'Noto Sans Buhid' },
	{ value: 'Noto Sans Carian, sans-serif', label: 'Noto Sans Carian' },
	{ value: 'Noto Sans Cham, sans-serif', label: 'Noto Sans Cham' },
	{ value: 'Noto Sans Cherokee, sans-serif', label: 'Noto Sans Cherokee' },
	{ value: 'Noto Sans Coptic, sans-serif', label: 'Noto Sans Coptic' },
	{
		value: 'Noto Sans Chorasmian, sans-serif',
		label: 'Noto Sans Chorasmian',
	},
	{
		value: 'Noto Sans Canadian Aboriginal, sans-serif',
		label: 'Noto Sans Canadian Aboriginal',
	},
	{
		value: 'Noto Sans Anatolian Hieroglyphs, sans-serif',
		label: 'Noto Sans Anatolian Hieroglyphs',
	},
	{
		value: 'Noto Sans Adlam Unjoined, sans-serif',
		label: 'Noto Sans Adlam Unjoined',
	},
	{ value: 'Ysabeau Infant, sans-serif', label: 'Ysabeau Infant' },
	{ value: 'Ysabeau Office, sans-serif', label: 'Ysabeau Office' },
	{ value: 'Be Vietnam Pro, sans-serif', label: 'Be Vietnam Pro' },
	{ value: 'Saira, sans-serif', label: 'Saira' },
	{ value: 'Orienta, sans-serif', label: 'Orienta' },
	{ value: 'Rokkitt, serif', label: 'Rokkitt' },
	{ value: 'Advent Pro, sans-serif', label: 'Advent Pro' },
	{ value: 'Inter Tight, sans-serif', label: 'Inter Tight' },
	{ value: 'Aleo, serif', label: 'Aleo' },
	{ value: 'Petrona, serif', label: 'Petrona' },
	{ value: 'Epilogue, sans-serif', label: 'Epilogue' },
	{ value: 'Taviraj, serif', label: 'Taviraj' },
	{ value: 'Albert Sans, sans-serif', label: 'Albert Sans' },
	{ value: 'Fraunces, serif', label: 'Fraunces' },
	{ value: 'Trirong, serif', label: 'Trirong' },
	{ value: 'Noto Serif Display, serif', label: 'Noto Serif Display' },
	{ value: 'Pathway Extreme, sans-serif', label: 'Pathway Extreme' },
	{ value: 'Hanken Grotesk, sans-serif', label: 'Hanken Grotesk' },
	{ value: 'Georama, sans-serif', label: 'Georama' },
	{ value: 'Sofia Sans, sans-serif', label: 'Sofia Sans' },
	{
		value: 'Sofia Sans Condensed, sans-serif',
		label: 'Sofia Sans Condensed',
	},
	{
		value: 'Sofia Sans Extra Condensed, sans-serif',
		label: 'Sofia Sans Extra Condensed',
	},
	{ value: 'Tomorrow, sans-serif', label: 'Tomorrow' },
	{ value: 'Chivo Mono, monospace', label: 'Chivo Mono' },
	{ value: 'Azeret Mono, monospace', label: 'Azeret Mono' },
	{ value: 'Gantari, sans-serif', label: 'Gantari' },
	{ value: 'Labrada, serif', label: 'Labrada' },
	{ value: 'Piazzolla, serif', label: 'Piazzolla' },
	{ value: 'Anybody, cursive', label: 'Anybody' },
	{ value: 'Texturina, serif', label: 'Texturina' },
	{ value: 'Grenze, serif', label: 'Grenze' },
	{ value: 'Niramit, sans-serif', label: 'Niramit' },
	{ value: 'Bai Jamjuree, sans-serif', label: 'Bai Jamjuree' },
	{ value: 'Krub, sans-serif', label: 'Krub' },
	{ value: 'Newsreader, serif', label: 'Newsreader' },
	{ value: 'JetBrains Mono, monospace', label: 'JetBrains Mono' },
	{ value: 'Yrsa, serif', label: 'Yrsa' },
	{ value: 'K2D, sans-serif', label: 'K2D' },
	{ value: 'Livvic, sans-serif', label: 'Livvic' },
	{ value: 'Pathway Extreme, sans-serif', label: 'Pathway Extreme' },
	{ value: 'Mali, cursive', label: 'Mali' },
	{ value: 'Wix Madefor Text, sans-serif', label: 'Wix Madefor Text' },
	{ value: 'Cormorant Infant, serif', label: 'Cormorant Infant' },
	{ value: 'Proza Libre, sans-serif', label: 'Proza Libre' },
	{ value: 'Rasa, serif', label: 'Rasa' },
	{ value: 'Bellefair, serif', label: 'Bellefair' },
	{ value: 'Vollkorn, serif', label: 'Vollkorn' },
	{ value: 'Cardo, serif', label: 'Cardo' },
	{ value: 'Caladea, serif', label: 'Caladea' },
	{ value: 'Mirza, serif', label: 'Mirza' },
	{ value: 'Castoro, serif', label: 'Castoro' },
	{ value: 'Caudex, serif', label: 'Caudex' },
	{ value: 'Charis SIL, serif', label: 'Charis SIL' },
	{ value: 'Cantata One, serif', label: 'Cantata One' },
	{ value: 'Rosario, sans-serif', label: 'Rosario' },
	{ value: 'Fahkwang, sans-serif', label: 'Fahkwang' },
	{ value: 'KoHo, sans-serif', label: 'KoHo' },
	{ value: 'Schibsted Grotesk, sans-serif', label: 'Schibsted Grotesk' },
	{ value: 'Radio Canada, sans-serif', label: 'Radio Canada' },
	{ value: 'Kulim Park, sans-serif', label: 'Kulim Park' },
	{ value: 'Kantumruy Pro, sans-serif', label: 'Kantumruy Pro' },
	{ value: 'Kumbh Sans, sans-serif', label: 'Kumbh Sans' },
	{ value: 'Mitr, sans-serif', label: 'Mitr' },
	{ value: 'Molengo, sans-serif', label: 'Molengo' },
	{ value: 'Monda, sans-serif', label: 'Monda' },
	{ value: 'Moulpali, sans-serif', label: 'Moulpali' },
	{ value: 'Mukta Malar, sans-serif', label: 'Mukta Malar' },
	{ value: 'Mukta Vaani, sans-serif', label: 'Mukta Vaani' },
	{ value: 'Murecho, sans-serif', label: 'Murecho' },
	{ value: 'League Spartan, sans-serif', label: 'League Spartan' },
	{ value: 'Lekton, sans-serif', label: 'Lekton' },
	{ value: 'Lexend, sans-serif', label: 'Lexend' },
	{ value: 'Lexend Deca, sans-serif', label: 'Lexend Deca' },
	{ value: 'Lexend Zetta, sans-serif', label: 'Lexend Zetta' },
	{ value: 'Lexend Giga, sans-serif', label: 'Lexend Giga' },
	{ value: 'Lexend Mega, sans-serif', label: 'Lexend Mega' },
	{ value: 'Lexend Peta, sans-serif', label: 'Lexend Peta' },
	{ value: 'Lexend Exa, sans-serif', label: 'Lexend Exa' },
	{ value: 'Lexend Tera, sans-serif', label: 'Lexend Tera' },
	{ value: 'Mohave, sans-serif', label: 'Mohave' },
	{ value: 'Roboto Flex, sans-serif', label: 'Roboto' },
	{ value: 'Source Sans 3, sans-serif', label: 'Source Sans 3' },
	{ value: 'Figtree, sans-serif', label: 'Figtree' },
	{ value: 'Plus Jakarta Sans, sans-serif', label: 'Plus Jakarta Sans' },
	{ value: 'Sarabun, sans-serif', label: 'Sarabun' },
	{ value: 'Belanosima, sans-serif', label: 'Belanosima' },
	{ value: 'Belleza, sans-serif', label: 'Belleza' },
	{ value: 'Biryani, sans-serif', label: 'Biryani' },
	{ value: 'Cambay, sans-serif', label: 'Cambay' },
	{ value: 'Candal, sans-serif', label: 'Candal' },
	{ value: 'Cantarell, sans-serif', label: 'Cantarell' },
	{ value: 'Cantora One, sans-serif', label: 'Cantora One' },
	{ value: 'Capriola, sans-serif', label: 'Capriola' },
	{ value: 'Carlito, sans-serif', label: 'Carlito' },
	{ value: 'Carme, sans-serif', label: 'Carme' },
	{ value: 'Carrois Gothic, sans-serif', label: 'Carrois Gothic' },
	{ value: 'Carrois Gothic SC, sans-serif', label: 'Carrois Gothic SC' },
	{ value: 'Catamaran, sans-serif', label: 'Catamaran' },
	{ value: 'Chakra Petch, sans-serif', label: 'Chakra Petch' },
	{ value: 'Changa, sans-serif', label: 'Changa' },
	{ value: 'Chathura, sans-serif', label: 'Chathura' },
	{ value: 'Chau Philomene One, sans-serif', label: 'Chau Philomene One' },
	{ value: 'Comme, sans-serif', label: 'Comme' },
	{ value: 'Commissioner, sans-serif', label: 'Commissioner' },
	{ value: 'Convergence, sans-serif', label: 'Convergence' },
	{ value: 'Farro, sans-serif', label: 'Farro' },
	{ value: 'Federo, sans-serif', label: 'Federo' },
	{ value: 'M PLUS 1, sans-serif', label: 'M PLUS 1' },
	{ value: 'M PLUS 2, sans-serif', label: 'M PLUS 2' },
	{ value: 'M PLUS 1p, sans-serif', label: 'M PLUS 1p' },
	{ value: 'M PLUS 1 Code, sans-serif', label: 'M PLUS 1 Code' },
	{ value: 'M PLUS Rounded 1c, sans-serif', label: 'M PLUS Rounded 1c' },
	{ value: 'Magra, sans-serif', label: 'Magra' },
	{ value: 'Mada, sans-serif', label: 'Mada' },
	{ value: 'Mako, sans-serif', label: 'Mako' },
	{ value: 'Narnoor, sans-serif', label: 'Narnoor' },
	{ value: 'News Cycle, sans-serif', label: 'News Cycle' },
	{ value: 'Nobile, sans-serif', label: 'Nobile' },
	{ value: 'Nokora, sans-serif', label: 'Nokora' },
	{ value: 'Noto Music, sans-serif', label: 'Noto Music' },
	{ value: 'Mallanna, sans-serif', label: 'Mallanna' },
	{ value: 'Mandali, sans-serif', label: 'Mandali' },
	{ value: 'Manjari, sans-serif', label: 'Manjari' },
	{ value: 'Finlandica, sans-serif', label: 'Finlandica' },
	{ value: 'Jaldi, sans-serif', label: 'Jaldi' },
	{ value: 'Meera Inimai, sans-serif', label: 'Meera Inimai' },
	{ value: 'Metrophobic, sans-serif', label: 'Metrophobic' },
	{ value: 'Michroma, sans-serif', label: 'Michroma' },
	{ value: 'Mingzat, sans-serif', label: 'Mingzat' },
	{ value: 'Jockey One, sans-serif', label: 'Jockey One' },
	{ value: 'Jura, sans-serif', label: 'Jura' },
	{ value: 'Kosugi, sans-serif', label: 'Kosugi' },
	{ value: 'Kosugi Maru, sans-serif', label: 'Kosugi Maru' },
	{ value: 'Changa One, cursive', label: 'Changa One' },
	{ value: 'Chango, cursive', label: 'Chango' },
	{ value: 'Chela One, cursive', label: 'Chela One' },
	{ value: 'Cherry Cream Soda, cursive', label: 'Cherry Cream Soda' },
	{ value: 'Chicle, cursive', label: 'Chicle' },
	{ value: 'Chonburi, cursive', label: 'Chonburi' },
	{ value: 'Coda, cursive', label: 'Coda' },
	{ value: 'Concert One, cursive', label: 'Concert One' },
	{ value: 'Expletus Sans, cursive', label: 'Expletus Sans' },
	{ value: 'Gugi, cursive', label: 'Gugi' },
	{ value: 'MuseoModerno, cursive', label: 'MuseoModerno' },
	{ value: 'Cousine, monospace', label: 'Cousine' },
	{ value: 'Martian Mono, monospace', label: 'Martian Mono' },
	{ value: 'Fira Mono, monospace', label: 'Fira Mono' },
	{ value: 'Bellota Text, cursive', label: 'Bellota Text' },
	{ value: 'Libre Barcode 128, cursive', label: 'Libre Barcode 128' },
	{
		value: 'Libre Barcode 128 Text, cursive',
		label: 'Libre Barcode 128 Text',
	},
	{ value: 'Libre Barcode 39, cursive', label: 'Libre Barcode 39' },
	{ value: 'Libre Barcode 39 Text, cursive', label: 'Libre Barcode 39 Text' },
	{
		value: 'Libre Barcode 39 Extended, cursive',
		label: 'Libre Barcode 39 Extended',
	},
	{
		value: 'Libre Barcode 39 Extended Text, cursive',
		label: 'Libre Barcode 39 Extended Text',
	},
	{
		value: 'Lilita One, cursive',
		label: 'Lilita One',
	},
];
export default fontOptions;
